<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="cs-114" name="Smoke Testcases" tests="4" failures="3" timestamp="27 Sep 2017 13:23:51 GMT" time="80.427" errors="0">
  <testcase name="BarcodeTest" time="16.976" classname="MobileCloudComputing.AppTest">
    <failure type="java.lang.AssertionError" message="java.lang.Exception: Internal Error. Could not load test case.">
      <![CDATA[java.lang.AssertionError: java.lang.Exception: Internal Error. Could not load test case.
	at MobileCloudComputing.AppTest.runTest(AppTest.java:111)
	at MobileCloudComputing.AppTest.BarcodeTest(AppTest.java:61)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- BarcodeTest -->
  <testcase name="LandscapeTest" time="15.289" classname="MobileCloudComputing.AppTest"/>
  <testcase name="LargeLandscapeTest" time="18.751" classname="MobileCloudComputing.AppTest">
    <failure type="java.lang.AssertionError" message="java.lang.Exception: Internal Error. Could not load test case.">
      <![CDATA[java.lang.AssertionError: java.lang.Exception: Internal Error. Could not load test case.
	at MobileCloudComputing.AppTest.runTest(AppTest.java:111)
	at MobileCloudComputing.AppTest.LargeLandscapeTest(AppTest.java:71)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- LargeLandscapeTest -->
  <testcase name="SelfieTest" time="17.438" classname="MobileCloudComputing.AppTest">
    <failure type="java.lang.AssertionError" message="java.lang.Exception: Internal Error. Could not load test case.">
      <![CDATA[java.lang.AssertionError: java.lang.Exception: Internal Error. Could not load test case.
	at MobileCloudComputing.AppTest.runTest(AppTest.java:111)
	at MobileCloudComputing.AppTest.SelfieTest(AppTest.java:56)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- SelfieTest -->
</testsuite> <!-- Smoke Testcases -->
